---
- name: Make sure /etc/kubernetes exists
  file:
    path: /etc/kubernetes
    state: directory

- name: Prepare openstack config file
  template:
    src: cloud-config.j2
    dest: /etc/kubernetes/cloud-config

- name: Check if kubelet config file needs change
  shell: grep -q "external" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  register: check_kubelet
  ignore_errors: True

- name: Modify kubelet arguments
  replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '(.*)KUBELET_KUBECONFIG_ARGS=(.*)$'
    replace: '\1KUBELET_KUBECONFIG_ARGS=--cloud-provider=external \2'
  when: check_kubelet.rc != 0

- name: restart kubelet service
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet

- name: Join to cluster
  shell: "{{ hostvars[groups['k8s_master'][0]]['join_str'] }}"
  when: bootstrap | bool
